import Button from 'components/uiKit/buttons'
import { LWSetupContext } from 'layouts/luckyWheel/setup'
import React, { useContext } from 'react'

export default function ApplyDefault() {
    const { setSelectedItem } = useContext(LWSetupContext)

    function applyDefault() {
        setSelectedItem({
            "id": 0,
            "internalName": "test",
            "internalDescription": "",
            "externalName": "",
            "externalId": "",
            "enabled": false,
            "brandId": 0,
            "startDate": "",
            "endDate": "",
            "isVisible": false,
            "widgetImage": "",
            "tierScale": "[0.9,0.65,0.4,0.2]",
            "renderStripes": "[true,true,true,true]",
            "borderColor": "#FFFFFFFF",
            "borderWidth": 4,
            "animationSpins": 8,
            "animationDuration": 8,
            "dot": {
                "id": 0,
                "color": "#FFFFFFFF",
                "shadow": "#000000FF",
                "size": 50,
                "classPrefix": "",
                "render": "[true,false,false,false]"
            },
            "ticker": {
                "id": 0,
                "color": "#FFFFFFFF",
                "shadow": "#000000FF",
                "size": 8,
                "classPrefix": "",
                "render": "true"
            },
            "wheelSegments": [
                {
                    "id": "temp-id-1-0",
                    "order": 0,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🎰",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FBF8CC",
                    "endBgColor": "#FDE4CF",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-1",
                    "order": 1,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🃏",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FFCFD2",
                    "endBgColor": "#F1C0E8",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-2",
                    "order": 2,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🪙",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#CFBAF0",
                    "endBgColor": "#A3C4F3",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-3",
                    "order": 3,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "♠️",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#90DBF4",
                    "endBgColor": "#8EECF5",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-4",
                    "order": 4,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "♥️",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#98F5E1",
                    "endBgColor": "#B9FBC0",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-5",
                    "order": 5,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "♦️",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FBF8CC",
                    "endBgColor": "#FFCFD2",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-6",
                    "order": 6,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "♣️",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FDE4CF",
                    "endBgColor": "#F1C0E8",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-7",
                    "order": 7,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🎲",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#A3C4F3",
                    "endBgColor": "#90DBF4",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-8",
                    "order": 8,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "💰",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#8EECF5",
                    "endBgColor": "#98F5E1",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-9",
                    "order": 9,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🏆",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#B9FBC0",
                    "endBgColor": "#FBF8CC",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-10",
                    "order": 10,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🎯",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FFC300FF",
                    "endBgColor": "#F1C0E8",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-1-11",
                    "order": 11,
                    "tier": 1,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🏮",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#CFBAF0",
                    "endBgColor": "#A3C4F3",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-2-0",
                    "order": 0,
                    "tier": 2,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🪅",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#90DBF4",
                    "endBgColor": "#8EECF5",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-2-1",
                    "order": 1,
                    "tier": 2,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🎉",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#98F5E1",
                    "endBgColor": "#B9FBC0",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-2-2",
                    "order": 2,
                    "tier": 2,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🔮",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FBF8CC",
                    "endBgColor": "#FFCFD2",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-2-3",
                    "order": 3,
                    "tier": 2,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🧩",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FDE4CF",
                    "endBgColor": "#F1C0E8",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-2-4",
                    "order": 4,
                    "tier": 2,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🕹️",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#CFBAF0",
                    "endBgColor": "#A3C4F3",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-2-5",
                    "order": 5,
                    "tier": 2,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🎫",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#90DBF4",
                    "endBgColor": "#8EECF5",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-3-0",
                    "order": 0,
                    "tier": 3,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "💎",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#98F5E1",
                    "endBgColor": "#B9FBC0",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-3-1",
                    "order": 1,
                    "tier": 3,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "🥇",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FBF8CC",
                    "endBgColor": "#FFCFD2",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-3-2",
                    "order": 2,
                    "tier": 3,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "📀",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#FDE4CF",
                    "endBgColor": "#F1C0E8",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                },
                {
                    "id": "temp-id-4-0",
                    "order": 0,
                    "tier": 4,
                    "colour": "",
                    "icon": "",
                    "probability": 0,
                    "isRespin": false,
                    "isNextTier": false,
                    "payoutId": "",
                    "text": "💵",
                    "textStyles": "",
                    "iconStyles": "",
                    "startBgColor": "#CFBAF0",
                    "endBgColor": "#A3C4F3",
                    "bgImage": "",
                    "classPrefix": "",
                    "winMessageContent": ""
                }
            ]
        })
    }


    return (
        <Button id='apply-default-cta' onClick={() => applyDefault()}>
            create default
        </Button>
    )
}
