export interface SsrProps {
    jwtToken?: string,
}
export type locales = 'en-GB' | 'es-ES' | 'fr-FR' | 'pt-BR'
export type themes = 'light' | 'dark'

export interface statesInfoInterface {
    id: string,
    name: string,
    blocked: boolean,
}
export interface countryInfoInterface {
    blocked: boolean,
    id: number,
    iso2Code: string,
    iso3Code: string,
    keyword: string,
    name: string,
    orderNumber: number,
    prefix: string,
    states: Array<statesInfoInterface>
}
export type Enumerate<N extends number, Acc extends number[] = []> = Acc['length'] extends N
    ? Acc[number]
    : Enumerate<N, [...Acc, Acc['length']]>

export type IntRange<F extends number, T extends number> = Exclude<Enumerate<T>, Enumerate<F>>
export type breakPointsType = 'xsm' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl'
export type flexJustifyContent = 'flex-start' | 'center' | 'flex-end' | 'space-around' | 'space-between' | 'stretch'
export type flexAlignContent = 'baseline' | 'center' | 'flex-end' | 'flex-start' | 'space-between' | 'stretch'

export type elementsMargin = (
    'm-1'
    | 'm-2'
    | 'm-3'
    | 'm-4'
    | 'm-5'
    | 'mt-1'
    | 'mt-2'
    | 'mt-3'
    | 'mt-4'
    | 'mt-5'
    | 'mb-1'
    | 'mb-2'
    | 'mb-3'
    | 'mb-4'
    | 'mb-5'
    | 'ms-1'
    | 'ms-2'
    | 'ms-3'
    | 'ms-4'
    | 'ms-5'
    | 'me-1'
    | 'me-2'
    | 'me-3'
    | 'me-4'
    | 'me-5'
    | 'm-md-1'
    | 'm-md-2'
    | 'm-md-3'
    | 'm-md-4'
    | 'm-md-5'
    | 'mt-md-1'
    | 'mt-md-2'
    | 'mt-md-3'
    | 'mt-md-4'
    | 'mt-md-5'
    | 'mb-md-1'
    | 'mb-md-2'
    | 'mb-md-3'
    | 'mb-md-4'
    | 'mb-md-5'
    | 'ms-md-1'
    | 'ms-md-2'
    | 'ms-md-3'
    | 'ms-md-4'
    | 'ms-md-5'
    | 'me-md-1'
    | 'me-md-2'
    | 'me-md-3'
    | 'me-md-4'
    | 'me-md-5'
    | 'm-lg-1'
    | 'm-lg-2'
    | 'm-lg-3'
    | 'm-lg-4'
    | 'm-lg-5'
    | 'mt-lg-1'
    | 'mt-lg-2'
    | 'mt-lg-3'
    | 'mt-lg-4'
    | 'mt-lg-5'
    | 'mb-lg-1'
    | 'mb-lg-2'
    | 'mb-lg-3'
    | 'mb-lg-4'
    | 'mb-lg-5'
    | 'ms-lg-1'
    | 'ms-lg-2'
    | 'ms-lg-3'
    | 'ms-lg-4'
    | 'ms-lg-5'
    | 'me-lg-1'
    | 'me-lg-2'
    | 'me-lg-3'
    | 'me-lg-4'
    | 'me-lg-5'
)

export type elementsPadding = (
    'p-0'
    | 'p-1'
    | 'p-2'
    | 'p-3'
    | 'p-4'
    | 'p-5'
    | 'pt-0'
    | 'pt-1'
    | 'pt-2'
    | 'pt-3'
    | 'pt-4'
    | 'pt-5'
    | 'pb-0'
    | 'pb-1'
    | 'pb-2'
    | 'pb-3'
    | 'pb-4'
    | 'pb-5'
    | 'ps-0'
    | 'ps-1'
    | 'ps-2'
    | 'ps-3'
    | 'ps-4'
    | 'ps-5'
    | 'pe-0'
    | 'pe-1'
    | 'pe-2'
    | 'pe-3'
    | 'pe-4'
    | 'pe-5'
    | 'p-md-0'
    | 'p-md-1'
    | 'p-md-2'
    | 'p-md-3'
    | 'p-md-4'
    | 'p-md-5'
    | 'pt-md-0'
    | 'pt-md-1'
    | 'pt-md-2'
    | 'pt-md-3'
    | 'pt-md-4'
    | 'pt-md-5'
    | 'pb-md-0'
    | 'pb-md-1'
    | 'pb-md-2'
    | 'pb-md-3'
    | 'pb-md-4'
    | 'pb-md-5'
    | 'ps-md-0'
    | 'ps-md-1'
    | 'ps-md-2'
    | 'ps-md-3'
    | 'ps-md-4'
    | 'ps-md-5'
    | 'pe-md-0'
    | 'pe-md-1'
    | 'pe-md-2'
    | 'pe-md-3'
    | 'pe-md-4'
    | 'pe-md-5'
    | 'p-lg-1'
    | 'p-lg-2'
    | 'p-lg-3'
    | 'p-lg-4'
    | 'p-lg-5'
    | 'pt-lg-1'
    | 'pt-lg-2'
    | 'pt-lg-3'
    | 'pt-lg-4'
    | 'pt-lg-5'
    | 'pb-lg-1'
    | 'pb-lg-2'
    | 'pb-lg-3'
    | 'pb-lg-4'
    | 'pb-lg-5'
    | 'ps-lg-1'
    | 'ps-lg-2'
    | 'ps-lg-3'
    | 'ps-lg-4'
    | 'ps-lg-5'
    | 'pe-lg-1'
    | 'pe-lg-2'
    | 'pe-lg-3'
    | 'pe-lg-4'
    | 'pe-lg-5'
)
