declare global {
    interface Window {
        joobaLW: any;
        gsap: any;
    }
}

export type Segment = {
    icon?: string;
    text?: string;
    background: string;
    color: string;
};

export type WheelConfig = {
    wheelContainer: HTMLElement;
    wheelId: string;
    segments: Segment[];
    wheelSize?: number;
};

export type SpinConfig = {
    wheel: HTMLElement;
    winnerIndex: number;
    spins: number;
    duration?: number;
    bounce?: {
        amplitude: number;
        frequency: number;
    };
};

export type MultipleWheelsConfig = {
    container: HTMLElement;
    configurations: Array<{
        segments: Segment[];
        sizeMultiplier: number;
    }>;
    wrapperSize: number;
};

export type settings = {
    log?: boolean;
    readyToMount?: boolean;
}

export type init = {
    settings: settings;
    wheelSettings: MultipleWheelsConfig;
}

export interface CSSProperties {
    alignContent?: string | undefined;
    alignItems?: string | undefined;
    alignSelf?: string | undefined;
    alignmentBaseline?: string | undefined;
    all?: string | undefined;
    animation?: string | undefined;
    animationDelay?: string | undefined;
    animationDirection?: string | undefined;
    animationDuration?: string | undefined;
    animationFillMode?: string | undefined;
    animationIterationCount?: string | undefined;
    animationName?: string | undefined;
    animationPlayState?: string | undefined;
    animationTimingFunction?: string | undefined;
    backfaceVisibility?: string | undefined;
    background?: string | undefined;
    backgroundAttachment?: string | undefined;
    backgroundBlendMode?: string | undefined;
    backgroundClip?: string | undefined;
    backgroundColor?: string | undefined;
    backgroundImage?: string | undefined;
    backgroundOrigin?: string | undefined;
    backgroundPosition?: string | undefined;
    backgroundPositionX?: string | undefined;
    backgroundPositionY?: string | undefined;
    backgroundRepeat?: string | undefined;
    backgroundSize?: string | undefined;
    baselineShift?: string | undefined;
    blockSize?: string | undefined;
    border?: string | undefined;
    borderBlockEnd?: string | undefined;
    borderBlockEndColor?: string | undefined;
    borderBlockEndStyle?: string | undefined;
    borderBlockEndWidth?: string | undefined;
    borderBlockStart?: string | undefined;
    borderBlockStartColor?: string | undefined;
    borderBlockStartStyle?: string | undefined;
    borderBlockStartWidth?: string | undefined;
    borderBottom?: string | undefined;
    borderBottomColor?: string | undefined;
    borderBottomLeftRadius?: string | undefined;
    borderBottomRightRadius?: string | undefined;
    borderBottomStyle?: string | undefined;
    borderBottomWidth?: string | undefined;
    borderCollapse?: string | undefined;
    borderColor?: string | undefined;
    borderImage?: string | undefined;
    borderImageOutset?: string | undefined;
    borderImageRepeat?: string | undefined;
    borderImageSlice?: string | undefined;
    borderImageSource?: string | undefined;
    borderImageWidth?: string | undefined;
    borderInlineEnd?: string | undefined;
    borderInlineEndColor?: string | undefined;
    borderInlineEndStyle?: string | undefined;
    borderInlineEndWidth?: string | undefined;
    borderInlineStart?: string | undefined;
    borderInlineStartColor?: string | undefined;
    borderInlineStartStyle?: string | undefined;
    borderInlineStartWidth?: string | undefined;
    borderLeft?: string | undefined;
    borderLeftColor?: string | undefined;
    borderLeftStyle?: string | undefined;
    borderLeftWidth?: string | undefined;
    borderRight?: string | undefined;
    borderRightColor?: string | undefined;
    borderRightStyle?: string | undefined;
    borderRightWidth?: string | undefined;
    borderSpacing?: string | undefined;
    borderStyle?: string | undefined;
    borderTop?: string | undefined;
    borderTopColor?: string | undefined;
    borderTopLeftRadius?: string | undefined;
    borderTopRightRadius?: string | undefined;
    borderTopStyle?: string | undefined;
    borderTopWidth?: string | undefined;
    borderWidth?: string | undefined;
    bottom?: string | number | undefined;
    boxShadow?: string | undefined;
    boxSizing?: string | undefined;
    breakAfter?: string | undefined;
    breakBefore?: string | undefined;
    breakInside?: string | undefined;
    captionSide?: string | undefined;
    caretColor?: string | undefined;
    clear?: string | undefined;
    clip?: string | undefined;
    clipPath?: string | undefined;
    clipRule?: string | undefined;
    color?: string | undefined;
    colorAdjust?: string | undefined;
    columnCount?: string | undefined;
    columnFill?: string | undefined;
    columnGap?: string | undefined;
    columnRule?: string | undefined;
    columnRuleColor?: string | undefined;
    columnRuleStyle?: string | undefined;
    columnRuleWidth?: string | undefined;
    columnSpan?: string | undefined;
    columnWidth?: string | undefined;
    columns?: string | undefined;
    content?: string | undefined;
    counterIncrement?: string | undefined;
    counterReset?: string | undefined;
    cssFloat?: string | undefined;
    cssText?: string | undefined;
    cursor?: string | undefined;
    direction?: string | undefined;
    display?: string | undefined;
    dominantBaseline?: string | undefined;
    emptyCells?: string | undefined;
    fill?: string | undefined;
    fillOpacity?: string | undefined;
    fillRule?: string | undefined;
    filter?: string | undefined;
    flex?: string | undefined;
    flexBasis?: string | undefined;
    flexDirection?: string | undefined;
    flexFlow?: string | undefined;
    flexGrow?: string | undefined;
    flexShrink?: string | undefined;
    flexWrap?: string | undefined;
    float?: string | undefined;
    floodColor?: string | undefined;
    floodOpacity?: string | undefined;
    font?: string | undefined;
    fontFamily?: string | undefined;
    fontFeatureSettings?: string | undefined;
    fontKerning?: string | undefined;
    fontSize?: string | undefined;
    fontSizeAdjust?: string | undefined;
    fontStretch?: string | undefined;
    fontStyle?: string | undefined;
    fontSynthesis?: string | undefined;
    fontVariant?: string | undefined;
    fontVariantCaps?: string | undefined;
    fontVariantEastAsian?: string | undefined;
    fontVariantLigatures?: string | undefined;
    fontVariantNumeric?: string | undefined;
    fontVariantPosition?: string | undefined;
    fontWeight?: string | undefined;
    gap?: string | undefined;
    glyphOrientationVertical?: string | undefined;
    grid?: string | undefined;
    gridArea?: string | undefined;
    gridAutoColumns?: string | undefined;
    gridAutoFlow?: string | undefined;
    gridAutoRows?: string | undefined;
    gridColumn?: string | undefined;
    gridColumnEnd?: string | undefined;
    gridColumnGap?: string | undefined;
    gridColumnStart?: string | undefined;
    gridGap?: string | undefined;
    gridRow?: string | undefined;
    gridRowEnd?: string | undefined;
    gridRowGap?: string | undefined;
    gridRowStart?: string | undefined;
    gridTemplate?: string | undefined;
    gridTemplateAreas?: string | undefined;
    gridTemplateColumns?: string | undefined;
    gridTemplateRows?: string | undefined;
    height?: string | number | undefined;
    hyphens?: string | undefined;
    imageOrientation?: string | undefined;
    imageRendering?: string | undefined;
    inlineSize?: string | undefined;
    inset?: string | undefined;
    insetBlock?: string | undefined;
    insetBlockEnd?: string | undefined;
    insetBlockStart?: string | undefined;
    insetInline?: string | undefined;
    insetInlineEnd?: string | undefined;
    insetInlineStart?: string | undefined;
    isolation?: string | undefined;
    justifyContent?: string | undefined;
    justifyItems?: string | undefined;
    justifySelf?: string | undefined;
    left?: string | number | undefined;
    letterSpacing?: string | undefined;
    lightingColor?: string | undefined;
    lineHeight?: string | number | undefined;
    listStyle?: string | undefined;
    listStyleImage?: string | undefined;
    listStylePosition?: string | undefined;
    listStyleType?: string | undefined;
    margin?: string | number | undefined;
    marginBlock?: string | undefined;
    marginBlockEnd?: string | undefined;
    marginBlockStart?: string | undefined;
    marginBottom?: string | number | undefined;
    marginInline?: string | undefined;
    marginInlineEnd?: string | undefined;
    marginInlineStart?: string | undefined;
    marginLeft?: string | number | undefined;
    marginRight?: string | number | undefined;
    marginTop?: string | number | undefined;
    marker?: string | undefined;
    markerEnd?: string | undefined;
    markerMid?: string | undefined;
    markerStart?: string | undefined;
    mask?: string | undefined;
    maskComposite?: string | undefined;
    maskImage?: string | undefined;
    maskPosition?: string | undefined;
    maskRepeat?: string | undefined;
    maskSize?: string | undefined;
    maskType?: string | undefined;
    maxBlockSize?: string | undefined;
    maxHeight?: string | number | undefined;
    maxInlineSize?: string | undefined;
    maxWidth?: string | number | undefined;
    minBlockSize?: string | undefined;
    minHeight?: string | number | undefined;
    minInlineSize?: string | undefined;
    minWidth?: string | number | undefined;
    mixBlendMode?: string | undefined;
    motion?: string | undefined;
    motionDistance?: string | undefined;
    motionPath?: string | undefined;
    motionRotation?: string | undefined;
    objectFit?: string | undefined;
    objectPosition?: string | undefined;
    offset?: string | undefined;
    offsetDistance?: string | undefined;
    offsetPath?: string | undefined;
    offsetRotate?: string | undefined;
    opacity?: string | number | undefined;
    order?: string | undefined;
    orphans?: string | undefined;
    outline?: string | undefined;
    outlineColor?: string | undefined;
    outlineOffset?: string | undefined;
    outlineStyle?: string | undefined;
    outlineWidth?: string | undefined;
    overflow?: string | undefined;
    overflowAnchor?: string | undefined;
    overflowClipBox?: string | undefined;
    overflowWrap?: string | undefined;
    overflowX?: string | undefined;
    overflowY?: string | undefined;
    overscrollBehavior?: string | undefined;
    overscrollBehaviorBlock?: string | undefined;
    overscrollBehaviorInline?: string | undefined;
    overscrollBehaviorX?: string | undefined;
    overscrollBehaviorY?: string | undefined;
    padding?: string | number | undefined;
    paddingBlock?: string | undefined;
    paddingBlockEnd?: string | undefined;
    paddingBlockStart?: string | undefined;
    paddingBottom?: string | number | undefined;
    paddingInline?: string | undefined;
    paddingInlineEnd?: string | undefined;
    paddingInlineStart?: string | undefined;
    paddingLeft?: string | number | undefined;
    paddingRight?: string | number | undefined;
    paddingTop?: string | number | undefined;
    pageBreakAfter?: string | undefined;
    pageBreakBefore?: string | undefined;
    pageBreakInside?: string | undefined;
    paintOrder?: string | undefined;
    perspective?: string | undefined;
    perspectiveOrigin?: string | undefined;
    placeContent?: string | undefined;
    placeItems?: string | undefined;
    placeSelf?: string | undefined;
    pointerEvents?: string | undefined;
    position?: string | undefined;
    quotes?: string | undefined;
    resize?: string | undefined;
    right?: string | number | undefined;
    rotate?: string | undefined;
    rowGap?: string | undefined;
    rubyAlign?: string | undefined;
    rubyMerge?: string | undefined;
    rubyPosition?: string | undefined;
    scale?: string | undefined;
    scrollBehavior?: string | undefined;
    shapeRendering?: string | undefined;
    stopColor?: string | undefined;
    stopOpacity?: string | undefined;
    stroke?: string | undefined;
    strokeDasharray?: string | undefined;
    strokeDashoffset?: string | undefined;
    strokeLinecap?: string | undefined;
    strokeLinejoin?: string | undefined;
    strokeMiterlimit?: string | undefined;
    strokeOpacity?: string | undefined;
    strokeWidth?: string | undefined;
    tabSize?: string | undefined;
    tableLayout?: string | undefined;
    textAlign?: string | undefined;
    textAlignLast?: string | undefined;
    textAnchor?: string | undefined;
    textCombineUpright?: string | undefined;
    textDecoration?: string | undefined;
    textDecorationColor?: string | undefined;
    textDecorationLine?: string | undefined;
    textDecorationSkip?: string | undefined;
    textDecorationSkipInk?: string | undefined;
    textDecorationStyle?: string | undefined;
    textDecorationThickness?: string | undefined;
    textDecorationWidth?: string | undefined;
    textEmphasis?: string | undefined;
    textEmphasisColor?: string | undefined;
    textEmphasisPosition?: string | undefined;
    textEmphasisStyle?: string | undefined;
    textIndent?: string | undefined;
    textJustify?: string | undefined;
    textOrientation?: string | undefined;
    textOverflow?: string | undefined;
    textRendering?: string | undefined;
    textShadow?: string | undefined;
    textSizeAdjust?: string | undefined;
    textTransform?: string | undefined;
    textUnderlinePosition?: string | undefined;
    top?: string | number | undefined;
    touchAction?: string | undefined;
    transform?: string | undefined;
    transformBox?: string | undefined;
    transformOrigin?: string | undefined;
    transformStyle?: string | undefined;
    transition?: string | undefined;
    transitionDelay?: string | undefined;
    transitionDuration?: string | undefined;
    transitionProperty?: string | undefined;
    transitionTimingFunction?: string | undefined;
    translate?: string | undefined;
    unicodeBidi?: string | undefined;
    userSelect?: string | undefined;
    verticalAlign?: string | undefined;
    visibility?: string | undefined;
    whiteSpace?: string | undefined;
    widows?: string | undefined;
    width?: string | number | undefined;
    willChange?: string | undefined;
    wordBreak?: string | undefined;
    wordSpacing?: string | undefined;
    wordWrap?: string | undefined;
    writingMode?: string | undefined;
    zIndex?: string | number | undefined;
    zoom?: string | undefined;
    [index: string]: any | undefined;
}
