/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1JackpotsIndexRouteImport } from './routes/api/v1/jackpots/index'
import { Route as ApiV1JackpotsTopupRouteImport } from './routes/api/v1/jackpots/topup'
import { Route as ApiV1JackpotsIdRouteImport } from './routes/api/v1/jackpots/$id'
import { Route as ApiV1EventSimulateBetRouteImport } from './routes/api/v1/event/simulate-bet'
import { Route as ApiV1EventSimulateRouteImport } from './routes/api/v1/event/simulate'
import { Route as ApiV1JackpotsEnableIdRouteImport } from './routes/api/v1/jackpots/enable.$id'
import { Route as ApiV1JackpotsDisableIdRouteImport } from './routes/api/v1/jackpots/disable.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsIndexRoute = ApiV1JackpotsIndexRouteImport.update({
  id: '/api/v1/jackpots/',
  path: '/api/v1/jackpots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsTopupRoute = ApiV1JackpotsTopupRouteImport.update({
  id: '/api/v1/jackpots/topup',
  path: '/api/v1/jackpots/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsIdRoute = ApiV1JackpotsIdRouteImport.update({
  id: '/api/v1/jackpots/$id',
  path: '/api/v1/jackpots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventSimulateBetRoute = ApiV1EventSimulateBetRouteImport.update({
  id: '/api/v1/event/simulate-bet',
  path: '/api/v1/event/simulate-bet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventSimulateRoute = ApiV1EventSimulateRouteImport.update({
  id: '/api/v1/event/simulate',
  path: '/api/v1/event/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsEnableIdRoute = ApiV1JackpotsEnableIdRouteImport.update({
  id: '/api/v1/jackpots/enable/$id',
  path: '/api/v1/jackpots/enable/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsDisableIdRoute = ApiV1JackpotsDisableIdRouteImport.update({
  id: '/api/v1/jackpots/disable/$id',
  path: '/api/v1/jackpots/disable/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1/event/simulate': typeof ApiV1EventSimulateRoute
  '/api/v1/event/simulate-bet': typeof ApiV1EventSimulateBetRoute
  '/api/v1/jackpots/$id': typeof ApiV1JackpotsIdRoute
  '/api/v1/jackpots/topup': typeof ApiV1JackpotsTopupRoute
  '/api/v1/jackpots/': typeof ApiV1JackpotsIndexRoute
  '/api/v1/jackpots/disable/$id': typeof ApiV1JackpotsDisableIdRoute
  '/api/v1/jackpots/enable/$id': typeof ApiV1JackpotsEnableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1/event/simulate': typeof ApiV1EventSimulateRoute
  '/api/v1/event/simulate-bet': typeof ApiV1EventSimulateBetRoute
  '/api/v1/jackpots/$id': typeof ApiV1JackpotsIdRoute
  '/api/v1/jackpots/topup': typeof ApiV1JackpotsTopupRoute
  '/api/v1/jackpots': typeof ApiV1JackpotsIndexRoute
  '/api/v1/jackpots/disable/$id': typeof ApiV1JackpotsDisableIdRoute
  '/api/v1/jackpots/enable/$id': typeof ApiV1JackpotsEnableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1/event/simulate': typeof ApiV1EventSimulateRoute
  '/api/v1/event/simulate-bet': typeof ApiV1EventSimulateBetRoute
  '/api/v1/jackpots/$id': typeof ApiV1JackpotsIdRoute
  '/api/v1/jackpots/topup': typeof ApiV1JackpotsTopupRoute
  '/api/v1/jackpots/': typeof ApiV1JackpotsIndexRoute
  '/api/v1/jackpots/disable/$id': typeof ApiV1JackpotsDisableIdRoute
  '/api/v1/jackpots/enable/$id': typeof ApiV1JackpotsEnableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/v1/event/simulate'
    | '/api/v1/event/simulate-bet'
    | '/api/v1/jackpots/$id'
    | '/api/v1/jackpots/topup'
    | '/api/v1/jackpots/'
    | '/api/v1/jackpots/disable/$id'
    | '/api/v1/jackpots/enable/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/v1/event/simulate'
    | '/api/v1/event/simulate-bet'
    | '/api/v1/jackpots/$id'
    | '/api/v1/jackpots/topup'
    | '/api/v1/jackpots'
    | '/api/v1/jackpots/disable/$id'
    | '/api/v1/jackpots/enable/$id'
  id:
    | '__root__'
    | '/'
    | '/api/v1/event/simulate'
    | '/api/v1/event/simulate-bet'
    | '/api/v1/jackpots/$id'
    | '/api/v1/jackpots/topup'
    | '/api/v1/jackpots/'
    | '/api/v1/jackpots/disable/$id'
    | '/api/v1/jackpots/enable/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1EventSimulateRoute: typeof ApiV1EventSimulateRoute
  ApiV1EventSimulateBetRoute: typeof ApiV1EventSimulateBetRoute
  ApiV1JackpotsIdRoute: typeof ApiV1JackpotsIdRoute
  ApiV1JackpotsTopupRoute: typeof ApiV1JackpotsTopupRoute
  ApiV1JackpotsIndexRoute: typeof ApiV1JackpotsIndexRoute
  ApiV1JackpotsDisableIdRoute: typeof ApiV1JackpotsDisableIdRoute
  ApiV1JackpotsEnableIdRoute: typeof ApiV1JackpotsEnableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/': {
      id: '/api/v1/jackpots/'
      path: '/api/v1/jackpots'
      fullPath: '/api/v1/jackpots/'
      preLoaderRoute: typeof ApiV1JackpotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/topup': {
      id: '/api/v1/jackpots/topup'
      path: '/api/v1/jackpots/topup'
      fullPath: '/api/v1/jackpots/topup'
      preLoaderRoute: typeof ApiV1JackpotsTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/$id': {
      id: '/api/v1/jackpots/$id'
      path: '/api/v1/jackpots/$id'
      fullPath: '/api/v1/jackpots/$id'
      preLoaderRoute: typeof ApiV1JackpotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/event/simulate-bet': {
      id: '/api/v1/event/simulate-bet'
      path: '/api/v1/event/simulate-bet'
      fullPath: '/api/v1/event/simulate-bet'
      preLoaderRoute: typeof ApiV1EventSimulateBetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/event/simulate': {
      id: '/api/v1/event/simulate'
      path: '/api/v1/event/simulate'
      fullPath: '/api/v1/event/simulate'
      preLoaderRoute: typeof ApiV1EventSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/enable/$id': {
      id: '/api/v1/jackpots/enable/$id'
      path: '/api/v1/jackpots/enable/$id'
      fullPath: '/api/v1/jackpots/enable/$id'
      preLoaderRoute: typeof ApiV1JackpotsEnableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/disable/$id': {
      id: '/api/v1/jackpots/disable/$id'
      path: '/api/v1/jackpots/disable/$id'
      fullPath: '/api/v1/jackpots/disable/$id'
      preLoaderRoute: typeof ApiV1JackpotsDisableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1EventSimulateRoute: ApiV1EventSimulateRoute,
  ApiV1EventSimulateBetRoute: ApiV1EventSimulateBetRoute,
  ApiV1JackpotsIdRoute: ApiV1JackpotsIdRoute,
  ApiV1JackpotsTopupRoute: ApiV1JackpotsTopupRoute,
  ApiV1JackpotsIndexRoute: ApiV1JackpotsIndexRoute,
  ApiV1JackpotsDisableIdRoute: ApiV1JackpotsDisableIdRoute,
  ApiV1JackpotsEnableIdRoute: ApiV1JackpotsEnableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
