/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxDemoRouteImport } from './routes/sandbox-demo'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSimulatorRouteImport } from './routes/admin.simulator'
import { Route as AdminJackpotsRouteImport } from './routes/admin.jackpots'
import { Route as AdminJackpotsIndexRouteImport } from './routes/admin.jackpots.index'
import { Route as AdminJackpotGroupsIndexRouteImport } from './routes/admin.jackpot-groups.index'
import { Route as AdminJackpotsNewRouteImport } from './routes/admin.jackpots.new'
import { Route as AdminJackpotGroupsIdRouteImport } from './routes/admin.jackpot-groups.$id'
import { Route as ApiV2JackpotsIndexRouteImport } from './routes/api/v2/jackpots/index'
import { Route as ApiV1JackpotsIndexRouteImport } from './routes/api/v1/jackpots/index'
import { Route as ApiV1JackpotGroupsIndexRouteImport } from './routes/api/v1/jackpot-groups/index'
import { Route as ApiV1JackpotsTopupRouteImport } from './routes/api/v1/jackpots/topup'
import { Route as ApiV1JackpotsIdRouteImport } from './routes/api/v1/jackpots/$id'
import { Route as ApiV1JackpotGroupsIdRouteImport } from './routes/api/v1/jackpot-groups/$id'
import { Route as ApiV1EventSimulateBetRouteImport } from './routes/api/v1/event/simulate-bet'
import { Route as ApiV1EventSimulateRouteImport } from './routes/api/v1/event/simulate'
import { Route as ApiV1EventBetRouteImport } from './routes/api/v1/event/bet'
import { Route as ApiV1JackpotsEnableIdRouteImport } from './routes/api/v1/jackpots/enable.$id'
import { Route as ApiV1JackpotsDisableIdRouteImport } from './routes/api/v1/jackpots/disable.$id'
import { Route as ApiV1JackpotsCloneIdRouteImport } from './routes/api/v1/jackpots/clone.$id'
import { Route as ApiV1JackpotGroupsIdStatusRouteImport } from './routes/api/v1/jackpot-groups/$id/status'
import { Route as ApiV1JackpotGroupsIdCloneRouteImport } from './routes/api/v1/jackpot-groups/$id/clone'
import { Route as ApiV1JackpotGroupsIdChildrenRouteImport } from './routes/api/v1/jackpot-groups/$id/children'
import { Route as ApiV1EventBetLedgerRouteImport } from './routes/api/v1/event/bet.ledger'

const SandboxDemoRoute = SandboxDemoRouteImport.update({
  id: '/sandbox-demo',
  path: '/sandbox-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSimulatorRoute = AdminSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJackpotsRoute = AdminJackpotsRouteImport.update({
  id: '/jackpots',
  path: '/jackpots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJackpotsIndexRoute = AdminJackpotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminJackpotsRoute,
} as any)
const AdminJackpotGroupsIndexRoute = AdminJackpotGroupsIndexRouteImport.update({
  id: '/jackpot-groups/',
  path: '/jackpot-groups/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJackpotsNewRoute = AdminJackpotsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminJackpotsRoute,
} as any)
const AdminJackpotGroupsIdRoute = AdminJackpotGroupsIdRouteImport.update({
  id: '/jackpot-groups/$id',
  path: '/jackpot-groups/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV2JackpotsIndexRoute = ApiV2JackpotsIndexRouteImport.update({
  id: '/api/v2/jackpots/',
  path: '/api/v2/jackpots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsIndexRoute = ApiV1JackpotsIndexRouteImport.update({
  id: '/api/v1/jackpots/',
  path: '/api/v1/jackpots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotGroupsIndexRoute = ApiV1JackpotGroupsIndexRouteImport.update({
  id: '/api/v1/jackpot-groups/',
  path: '/api/v1/jackpot-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsTopupRoute = ApiV1JackpotsTopupRouteImport.update({
  id: '/api/v1/jackpots/topup',
  path: '/api/v1/jackpots/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsIdRoute = ApiV1JackpotsIdRouteImport.update({
  id: '/api/v1/jackpots/$id',
  path: '/api/v1/jackpots/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotGroupsIdRoute = ApiV1JackpotGroupsIdRouteImport.update({
  id: '/api/v1/jackpot-groups/$id',
  path: '/api/v1/jackpot-groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventSimulateBetRoute = ApiV1EventSimulateBetRouteImport.update({
  id: '/api/v1/event/simulate-bet',
  path: '/api/v1/event/simulate-bet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventSimulateRoute = ApiV1EventSimulateRouteImport.update({
  id: '/api/v1/event/simulate',
  path: '/api/v1/event/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventBetRoute = ApiV1EventBetRouteImport.update({
  id: '/api/v1/event/bet',
  path: '/api/v1/event/bet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsEnableIdRoute = ApiV1JackpotsEnableIdRouteImport.update({
  id: '/api/v1/jackpots/enable/$id',
  path: '/api/v1/jackpots/enable/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsDisableIdRoute = ApiV1JackpotsDisableIdRouteImport.update({
  id: '/api/v1/jackpots/disable/$id',
  path: '/api/v1/jackpots/disable/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotsCloneIdRoute = ApiV1JackpotsCloneIdRouteImport.update({
  id: '/api/v1/jackpots/clone/$id',
  path: '/api/v1/jackpots/clone/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JackpotGroupsIdStatusRoute =
  ApiV1JackpotGroupsIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiV1JackpotGroupsIdRoute,
  } as any)
const ApiV1JackpotGroupsIdCloneRoute =
  ApiV1JackpotGroupsIdCloneRouteImport.update({
    id: '/clone',
    path: '/clone',
    getParentRoute: () => ApiV1JackpotGroupsIdRoute,
  } as any)
const ApiV1JackpotGroupsIdChildrenRoute =
  ApiV1JackpotGroupsIdChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => ApiV1JackpotGroupsIdRoute,
  } as any)
const ApiV1EventBetLedgerRoute = ApiV1EventBetLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => ApiV1EventBetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sandbox-demo': typeof SandboxDemoRoute
  '/admin/jackpots': typeof AdminJackpotsRouteWithChildren
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/jackpot-groups/$id': typeof AdminJackpotGroupsIdRoute
  '/admin/jackpots/new': typeof AdminJackpotsNewRoute
  '/admin/jackpot-groups/': typeof AdminJackpotGroupsIndexRoute
  '/admin/jackpots/': typeof AdminJackpotsIndexRoute
  '/api/v1/event/bet': typeof ApiV1EventBetRouteWithChildren
  '/api/v1/event/simulate': typeof ApiV1EventSimulateRoute
  '/api/v1/event/simulate-bet': typeof ApiV1EventSimulateBetRoute
  '/api/v1/jackpot-groups/$id': typeof ApiV1JackpotGroupsIdRouteWithChildren
  '/api/v1/jackpots/$id': typeof ApiV1JackpotsIdRoute
  '/api/v1/jackpots/topup': typeof ApiV1JackpotsTopupRoute
  '/api/v1/jackpot-groups/': typeof ApiV1JackpotGroupsIndexRoute
  '/api/v1/jackpots/': typeof ApiV1JackpotsIndexRoute
  '/api/v2/jackpots/': typeof ApiV2JackpotsIndexRoute
  '/api/v1/event/bet/ledger': typeof ApiV1EventBetLedgerRoute
  '/api/v1/jackpot-groups/$id/children': typeof ApiV1JackpotGroupsIdChildrenRoute
  '/api/v1/jackpot-groups/$id/clone': typeof ApiV1JackpotGroupsIdCloneRoute
  '/api/v1/jackpot-groups/$id/status': typeof ApiV1JackpotGroupsIdStatusRoute
  '/api/v1/jackpots/clone/$id': typeof ApiV1JackpotsCloneIdRoute
  '/api/v1/jackpots/disable/$id': typeof ApiV1JackpotsDisableIdRoute
  '/api/v1/jackpots/enable/$id': typeof ApiV1JackpotsEnableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sandbox-demo': typeof SandboxDemoRoute
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/jackpot-groups/$id': typeof AdminJackpotGroupsIdRoute
  '/admin/jackpots/new': typeof AdminJackpotsNewRoute
  '/admin/jackpot-groups': typeof AdminJackpotGroupsIndexRoute
  '/admin/jackpots': typeof AdminJackpotsIndexRoute
  '/api/v1/event/bet': typeof ApiV1EventBetRouteWithChildren
  '/api/v1/event/simulate': typeof ApiV1EventSimulateRoute
  '/api/v1/event/simulate-bet': typeof ApiV1EventSimulateBetRoute
  '/api/v1/jackpot-groups/$id': typeof ApiV1JackpotGroupsIdRouteWithChildren
  '/api/v1/jackpots/$id': typeof ApiV1JackpotsIdRoute
  '/api/v1/jackpots/topup': typeof ApiV1JackpotsTopupRoute
  '/api/v1/jackpot-groups': typeof ApiV1JackpotGroupsIndexRoute
  '/api/v1/jackpots': typeof ApiV1JackpotsIndexRoute
  '/api/v2/jackpots': typeof ApiV2JackpotsIndexRoute
  '/api/v1/event/bet/ledger': typeof ApiV1EventBetLedgerRoute
  '/api/v1/jackpot-groups/$id/children': typeof ApiV1JackpotGroupsIdChildrenRoute
  '/api/v1/jackpot-groups/$id/clone': typeof ApiV1JackpotGroupsIdCloneRoute
  '/api/v1/jackpot-groups/$id/status': typeof ApiV1JackpotGroupsIdStatusRoute
  '/api/v1/jackpots/clone/$id': typeof ApiV1JackpotsCloneIdRoute
  '/api/v1/jackpots/disable/$id': typeof ApiV1JackpotsDisableIdRoute
  '/api/v1/jackpots/enable/$id': typeof ApiV1JackpotsEnableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sandbox-demo': typeof SandboxDemoRoute
  '/admin/jackpots': typeof AdminJackpotsRouteWithChildren
  '/admin/simulator': typeof AdminSimulatorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/jackpot-groups/$id': typeof AdminJackpotGroupsIdRoute
  '/admin/jackpots/new': typeof AdminJackpotsNewRoute
  '/admin/jackpot-groups/': typeof AdminJackpotGroupsIndexRoute
  '/admin/jackpots/': typeof AdminJackpotsIndexRoute
  '/api/v1/event/bet': typeof ApiV1EventBetRouteWithChildren
  '/api/v1/event/simulate': typeof ApiV1EventSimulateRoute
  '/api/v1/event/simulate-bet': typeof ApiV1EventSimulateBetRoute
  '/api/v1/jackpot-groups/$id': typeof ApiV1JackpotGroupsIdRouteWithChildren
  '/api/v1/jackpots/$id': typeof ApiV1JackpotsIdRoute
  '/api/v1/jackpots/topup': typeof ApiV1JackpotsTopupRoute
  '/api/v1/jackpot-groups/': typeof ApiV1JackpotGroupsIndexRoute
  '/api/v1/jackpots/': typeof ApiV1JackpotsIndexRoute
  '/api/v2/jackpots/': typeof ApiV2JackpotsIndexRoute
  '/api/v1/event/bet/ledger': typeof ApiV1EventBetLedgerRoute
  '/api/v1/jackpot-groups/$id/children': typeof ApiV1JackpotGroupsIdChildrenRoute
  '/api/v1/jackpot-groups/$id/clone': typeof ApiV1JackpotGroupsIdCloneRoute
  '/api/v1/jackpot-groups/$id/status': typeof ApiV1JackpotGroupsIdStatusRoute
  '/api/v1/jackpots/clone/$id': typeof ApiV1JackpotsCloneIdRoute
  '/api/v1/jackpots/disable/$id': typeof ApiV1JackpotsDisableIdRoute
  '/api/v1/jackpots/enable/$id': typeof ApiV1JackpotsEnableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/reset-password'
    | '/sandbox-demo'
    | '/admin/jackpots'
    | '/admin/simulator'
    | '/admin/users'
    | '/admin/'
    | '/admin/jackpot-groups/$id'
    | '/admin/jackpots/new'
    | '/admin/jackpot-groups/'
    | '/admin/jackpots/'
    | '/api/v1/event/bet'
    | '/api/v1/event/simulate'
    | '/api/v1/event/simulate-bet'
    | '/api/v1/jackpot-groups/$id'
    | '/api/v1/jackpots/$id'
    | '/api/v1/jackpots/topup'
    | '/api/v1/jackpot-groups/'
    | '/api/v1/jackpots/'
    | '/api/v2/jackpots/'
    | '/api/v1/event/bet/ledger'
    | '/api/v1/jackpot-groups/$id/children'
    | '/api/v1/jackpot-groups/$id/clone'
    | '/api/v1/jackpot-groups/$id/status'
    | '/api/v1/jackpots/clone/$id'
    | '/api/v1/jackpots/disable/$id'
    | '/api/v1/jackpots/enable/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sandbox-demo'
    | '/admin/simulator'
    | '/admin/users'
    | '/admin'
    | '/admin/jackpot-groups/$id'
    | '/admin/jackpots/new'
    | '/admin/jackpot-groups'
    | '/admin/jackpots'
    | '/api/v1/event/bet'
    | '/api/v1/event/simulate'
    | '/api/v1/event/simulate-bet'
    | '/api/v1/jackpot-groups/$id'
    | '/api/v1/jackpots/$id'
    | '/api/v1/jackpots/topup'
    | '/api/v1/jackpot-groups'
    | '/api/v1/jackpots'
    | '/api/v2/jackpots'
    | '/api/v1/event/bet/ledger'
    | '/api/v1/jackpot-groups/$id/children'
    | '/api/v1/jackpot-groups/$id/clone'
    | '/api/v1/jackpot-groups/$id/status'
    | '/api/v1/jackpots/clone/$id'
    | '/api/v1/jackpots/disable/$id'
    | '/api/v1/jackpots/enable/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/reset-password'
    | '/sandbox-demo'
    | '/admin/jackpots'
    | '/admin/simulator'
    | '/admin/users'
    | '/admin/'
    | '/admin/jackpot-groups/$id'
    | '/admin/jackpots/new'
    | '/admin/jackpot-groups/'
    | '/admin/jackpots/'
    | '/api/v1/event/bet'
    | '/api/v1/event/simulate'
    | '/api/v1/event/simulate-bet'
    | '/api/v1/jackpot-groups/$id'
    | '/api/v1/jackpots/$id'
    | '/api/v1/jackpots/topup'
    | '/api/v1/jackpot-groups/'
    | '/api/v1/jackpots/'
    | '/api/v2/jackpots/'
    | '/api/v1/event/bet/ledger'
    | '/api/v1/jackpot-groups/$id/children'
    | '/api/v1/jackpot-groups/$id/clone'
    | '/api/v1/jackpot-groups/$id/status'
    | '/api/v1/jackpots/clone/$id'
    | '/api/v1/jackpots/disable/$id'
    | '/api/v1/jackpots/enable/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SandboxDemoRoute: typeof SandboxDemoRoute
  ApiV1EventBetRoute: typeof ApiV1EventBetRouteWithChildren
  ApiV1EventSimulateRoute: typeof ApiV1EventSimulateRoute
  ApiV1EventSimulateBetRoute: typeof ApiV1EventSimulateBetRoute
  ApiV1JackpotGroupsIdRoute: typeof ApiV1JackpotGroupsIdRouteWithChildren
  ApiV1JackpotsIdRoute: typeof ApiV1JackpotsIdRoute
  ApiV1JackpotsTopupRoute: typeof ApiV1JackpotsTopupRoute
  ApiV1JackpotGroupsIndexRoute: typeof ApiV1JackpotGroupsIndexRoute
  ApiV1JackpotsIndexRoute: typeof ApiV1JackpotsIndexRoute
  ApiV2JackpotsIndexRoute: typeof ApiV2JackpotsIndexRoute
  ApiV1JackpotsCloneIdRoute: typeof ApiV1JackpotsCloneIdRoute
  ApiV1JackpotsDisableIdRoute: typeof ApiV1JackpotsDisableIdRoute
  ApiV1JackpotsEnableIdRoute: typeof ApiV1JackpotsEnableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox-demo': {
      id: '/sandbox-demo'
      path: '/sandbox-demo'
      fullPath: '/sandbox-demo'
      preLoaderRoute: typeof SandboxDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/simulator': {
      id: '/admin/simulator'
      path: '/simulator'
      fullPath: '/admin/simulator'
      preLoaderRoute: typeof AdminSimulatorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jackpots': {
      id: '/admin/jackpots'
      path: '/jackpots'
      fullPath: '/admin/jackpots'
      preLoaderRoute: typeof AdminJackpotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jackpots/': {
      id: '/admin/jackpots/'
      path: '/'
      fullPath: '/admin/jackpots/'
      preLoaderRoute: typeof AdminJackpotsIndexRouteImport
      parentRoute: typeof AdminJackpotsRoute
    }
    '/admin/jackpot-groups/': {
      id: '/admin/jackpot-groups/'
      path: '/jackpot-groups'
      fullPath: '/admin/jackpot-groups/'
      preLoaderRoute: typeof AdminJackpotGroupsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jackpots/new': {
      id: '/admin/jackpots/new'
      path: '/new'
      fullPath: '/admin/jackpots/new'
      preLoaderRoute: typeof AdminJackpotsNewRouteImport
      parentRoute: typeof AdminJackpotsRoute
    }
    '/admin/jackpot-groups/$id': {
      id: '/admin/jackpot-groups/$id'
      path: '/jackpot-groups/$id'
      fullPath: '/admin/jackpot-groups/$id'
      preLoaderRoute: typeof AdminJackpotGroupsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v2/jackpots/': {
      id: '/api/v2/jackpots/'
      path: '/api/v2/jackpots'
      fullPath: '/api/v2/jackpots/'
      preLoaderRoute: typeof ApiV2JackpotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/': {
      id: '/api/v1/jackpots/'
      path: '/api/v1/jackpots'
      fullPath: '/api/v1/jackpots/'
      preLoaderRoute: typeof ApiV1JackpotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpot-groups/': {
      id: '/api/v1/jackpot-groups/'
      path: '/api/v1/jackpot-groups'
      fullPath: '/api/v1/jackpot-groups/'
      preLoaderRoute: typeof ApiV1JackpotGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/topup': {
      id: '/api/v1/jackpots/topup'
      path: '/api/v1/jackpots/topup'
      fullPath: '/api/v1/jackpots/topup'
      preLoaderRoute: typeof ApiV1JackpotsTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/$id': {
      id: '/api/v1/jackpots/$id'
      path: '/api/v1/jackpots/$id'
      fullPath: '/api/v1/jackpots/$id'
      preLoaderRoute: typeof ApiV1JackpotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpot-groups/$id': {
      id: '/api/v1/jackpot-groups/$id'
      path: '/api/v1/jackpot-groups/$id'
      fullPath: '/api/v1/jackpot-groups/$id'
      preLoaderRoute: typeof ApiV1JackpotGroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/event/simulate-bet': {
      id: '/api/v1/event/simulate-bet'
      path: '/api/v1/event/simulate-bet'
      fullPath: '/api/v1/event/simulate-bet'
      preLoaderRoute: typeof ApiV1EventSimulateBetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/event/simulate': {
      id: '/api/v1/event/simulate'
      path: '/api/v1/event/simulate'
      fullPath: '/api/v1/event/simulate'
      preLoaderRoute: typeof ApiV1EventSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/event/bet': {
      id: '/api/v1/event/bet'
      path: '/api/v1/event/bet'
      fullPath: '/api/v1/event/bet'
      preLoaderRoute: typeof ApiV1EventBetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/enable/$id': {
      id: '/api/v1/jackpots/enable/$id'
      path: '/api/v1/jackpots/enable/$id'
      fullPath: '/api/v1/jackpots/enable/$id'
      preLoaderRoute: typeof ApiV1JackpotsEnableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/disable/$id': {
      id: '/api/v1/jackpots/disable/$id'
      path: '/api/v1/jackpots/disable/$id'
      fullPath: '/api/v1/jackpots/disable/$id'
      preLoaderRoute: typeof ApiV1JackpotsDisableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpots/clone/$id': {
      id: '/api/v1/jackpots/clone/$id'
      path: '/api/v1/jackpots/clone/$id'
      fullPath: '/api/v1/jackpots/clone/$id'
      preLoaderRoute: typeof ApiV1JackpotsCloneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jackpot-groups/$id/status': {
      id: '/api/v1/jackpot-groups/$id/status'
      path: '/status'
      fullPath: '/api/v1/jackpot-groups/$id/status'
      preLoaderRoute: typeof ApiV1JackpotGroupsIdStatusRouteImport
      parentRoute: typeof ApiV1JackpotGroupsIdRoute
    }
    '/api/v1/jackpot-groups/$id/clone': {
      id: '/api/v1/jackpot-groups/$id/clone'
      path: '/clone'
      fullPath: '/api/v1/jackpot-groups/$id/clone'
      preLoaderRoute: typeof ApiV1JackpotGroupsIdCloneRouteImport
      parentRoute: typeof ApiV1JackpotGroupsIdRoute
    }
    '/api/v1/jackpot-groups/$id/children': {
      id: '/api/v1/jackpot-groups/$id/children'
      path: '/children'
      fullPath: '/api/v1/jackpot-groups/$id/children'
      preLoaderRoute: typeof ApiV1JackpotGroupsIdChildrenRouteImport
      parentRoute: typeof ApiV1JackpotGroupsIdRoute
    }
    '/api/v1/event/bet/ledger': {
      id: '/api/v1/event/bet/ledger'
      path: '/ledger'
      fullPath: '/api/v1/event/bet/ledger'
      preLoaderRoute: typeof ApiV1EventBetLedgerRouteImport
      parentRoute: typeof ApiV1EventBetRoute
    }
  }
}

interface AdminJackpotsRouteChildren {
  AdminJackpotsNewRoute: typeof AdminJackpotsNewRoute
  AdminJackpotsIndexRoute: typeof AdminJackpotsIndexRoute
}

const AdminJackpotsRouteChildren: AdminJackpotsRouteChildren = {
  AdminJackpotsNewRoute: AdminJackpotsNewRoute,
  AdminJackpotsIndexRoute: AdminJackpotsIndexRoute,
}

const AdminJackpotsRouteWithChildren = AdminJackpotsRoute._addFileChildren(
  AdminJackpotsRouteChildren,
)

interface AdminRouteChildren {
  AdminJackpotsRoute: typeof AdminJackpotsRouteWithChildren
  AdminSimulatorRoute: typeof AdminSimulatorRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminJackpotGroupsIdRoute: typeof AdminJackpotGroupsIdRoute
  AdminJackpotGroupsIndexRoute: typeof AdminJackpotGroupsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJackpotsRoute: AdminJackpotsRouteWithChildren,
  AdminSimulatorRoute: AdminSimulatorRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminJackpotGroupsIdRoute: AdminJackpotGroupsIdRoute,
  AdminJackpotGroupsIndexRoute: AdminJackpotGroupsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiV1EventBetRouteChildren {
  ApiV1EventBetLedgerRoute: typeof ApiV1EventBetLedgerRoute
}

const ApiV1EventBetRouteChildren: ApiV1EventBetRouteChildren = {
  ApiV1EventBetLedgerRoute: ApiV1EventBetLedgerRoute,
}

const ApiV1EventBetRouteWithChildren = ApiV1EventBetRoute._addFileChildren(
  ApiV1EventBetRouteChildren,
)

interface ApiV1JackpotGroupsIdRouteChildren {
  ApiV1JackpotGroupsIdChildrenRoute: typeof ApiV1JackpotGroupsIdChildrenRoute
  ApiV1JackpotGroupsIdCloneRoute: typeof ApiV1JackpotGroupsIdCloneRoute
  ApiV1JackpotGroupsIdStatusRoute: typeof ApiV1JackpotGroupsIdStatusRoute
}

const ApiV1JackpotGroupsIdRouteChildren: ApiV1JackpotGroupsIdRouteChildren = {
  ApiV1JackpotGroupsIdChildrenRoute: ApiV1JackpotGroupsIdChildrenRoute,
  ApiV1JackpotGroupsIdCloneRoute: ApiV1JackpotGroupsIdCloneRoute,
  ApiV1JackpotGroupsIdStatusRoute: ApiV1JackpotGroupsIdStatusRoute,
}

const ApiV1JackpotGroupsIdRouteWithChildren =
  ApiV1JackpotGroupsIdRoute._addFileChildren(ApiV1JackpotGroupsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SandboxDemoRoute: SandboxDemoRoute,
  ApiV1EventBetRoute: ApiV1EventBetRouteWithChildren,
  ApiV1EventSimulateRoute: ApiV1EventSimulateRoute,
  ApiV1EventSimulateBetRoute: ApiV1EventSimulateBetRoute,
  ApiV1JackpotGroupsIdRoute: ApiV1JackpotGroupsIdRouteWithChildren,
  ApiV1JackpotsIdRoute: ApiV1JackpotsIdRoute,
  ApiV1JackpotsTopupRoute: ApiV1JackpotsTopupRoute,
  ApiV1JackpotGroupsIndexRoute: ApiV1JackpotGroupsIndexRoute,
  ApiV1JackpotsIndexRoute: ApiV1JackpotsIndexRoute,
  ApiV2JackpotsIndexRoute: ApiV2JackpotsIndexRoute,
  ApiV1JackpotsCloneIdRoute: ApiV1JackpotsCloneIdRoute,
  ApiV1JackpotsDisableIdRoute: ApiV1JackpotsDisableIdRoute,
  ApiV1JackpotsEnableIdRoute: ApiV1JackpotsEnableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
